apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotify-app
  namespace: spotify-app
spec:
  replicas: 8
  selector:
    matchLabels:
      app: spotify
  template:
    metadata:
      labels:
        app: spotify
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
      containers:
        - name: spotify-container
          image: satya1541/spotify-clone:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spotify-app
  namespace: spotify-app
spec:
  type: LoadBalancer
  selector:
    app: spotify
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spotify-app-hpa
  namespace: spotify-app
spec:
  scaleTargetRef:
    kind: Deployment
    name: spotify-app
  minReplicas: 3
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70

