apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: netflix
  name: netflix-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
      - name: cont1
        image: satya1541/netflix:latest
        ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-app
spec:
  type: LoadBalancer
  selector:
    app: netflix
  ports:
    - port: 80
      targetPort: 80
